GoogleCloudPlatform/anthos-samples

troubleshooting/create_snapshot.py
This can be used to gather useful information available via the `kubectl` tool. It will be automatically packed into a .tar.gz snapshot file.
=> Initial draft of the snapshot creating script.

aws-logging-monitoring/README.md, aws-logging-monitoring/logging/aggregator.yaml, aws-logging-monitoring/logging/forwarder.yaml, aws-logging-monitoring/monitoring/prometheus.yaml, aws-logging-monitoring/monitoring/server-configmap.yaml, aws-logging-monitoring/monitoring/sidecar-configmap.yaml
Based off of the attached-logging-monitoring files.
=> Provide yamls to setup logmon on multicloud/aws

anthos-bm-openstack-terraform/main.tf
- Adjust settings to accommodate for added connectivity testing in pre-flight check
- Tested on ABM 1.7.1
- 
- Adjusted health check settings to lower the delay and timeout
=> Update health monitor check settings

anthos-multi-cloud/AWS/README.md, anthos-multi-cloud/Azure/README.md
Adjust readme repo links to their new home!
=> doc: correct readme repo links

anthos-multi-cloud/README.md
=> test: add new line

anthos-multi-cloud/AWS/modules/gcp_data/main.tf
in AWS example instead of Azure.
=> fix: use google_container_aws_versions data src

anthos-bm-openstack-terraform/docs/install_abm.md
=> doc: update install_abm.md

anthos-bm-gcp-terraform/README.md
- Update the terraform version guidance
- Change terraform version from <1.1 to <v1.2
- N/A
=> fix: update TF version range for abm sample

anthos-bm-gcp-terraform/README.md, anthos-bm-gcp-terraform/resources/init_vm.sh, anthos-bm-gcp-terraform/resources/templates/anthos_gce_cluster.tpl, anthos-bm-gcp-terraform/resources/templates/manuallb_cluster.tpl, anthos-bm-gcp-terraform/versions.tf, test/integration/abm_gce_defaults_on_editor_project/abm_gce_editor_test.go
- Update ABM to the latest version
- Update ABM to the latest version
- N/A
=> feat: Update ABM version to 1.11

CODEOWNERS
- Internal bug [b/228517537](http://b/228517537) requesting ABM team host some manifests in this repo for customer access
- Create a placeholder dir for the manifest files
- Update CODEOWNERS
- N/A
=> chore: add abm team as CODEOWNERS

anthos-bm-utils/abm-nettest/nettest.yaml, anthos-bm-utils/abm-nettest/nettest_rhel.yaml
=> chore: adds manifests for nettest.

anthos-bm-utils/README.md
- Add a readme for the newly added file
- Add a README file
- N/A
=> doc: add readme for anthos-baremetal-util

anthos-multi-cloud/AWS/README.md
removed project number reference
=> doc: update README.md for multicloud sample

anthos-bm-gcp-terraform/versions.tf
- Add min TF version for [anthos-bm-gcp-terraform] per README.md
=> fix: [anthos-bm-gcp-terraform] enforce min TF per README.md

anthos-bm-gcp-terraform/main.tf, anthos-bm-gcp-terraform/modules/loadbalancer/main.tf
- Changes to allow multiple [anthos-bm-gcp-terraform] instantiations in a single project
=> feat: add [anthos-bm-gcp-terraform] multiple instantiations

anthos-bm-gcp-terraform/docs/nfs.md
- Rearrange the docs added for the NFS Driver setup in PR https://github.com/GoogleCloudPlatform/anthos-samples/pull/258
- Change NFS README
- https://github.com/GoogleCloudPlatform/anthos-samples/pull/258
=> cleanup: improve the docs for the nfs setup

anthos-vmruntime/README.md, anthos-vmruntime/pos-vm.yaml
=> fix: [anthos-samples] update image

anthos-vmruntime/README.md
- Fix some broken links in the docs
- Update the links
- N/A
=> doc: fix broken links in the doc

anthos-bm-utils/abm-nettest/nettest.yaml, anthos-bm-utils/abm-nettest/nettest_rhel.yaml
- Fixes indentation issue in cloudprober config in nettest_rhel.yaml
=> fix: fixes issue where nettest fails on rhel with wrong cloudprober config

anthos-bm-gcp-terraform/main.tf
- Move to pessimistic constraint operator on minor versions to reduce module update PRs.
=> chore: move to pessimistic constraint operator

anthos-bm-utils/abm-nettest/nettest.yaml, anthos-bm-utils/abm-nettest/nettest_rhel.yaml
- Adds connectgateway public API endpoint to nettest manifests
=> chore: [nettest] Adds connectgateway public API endpoint

anthos-bm-edge-deployment/README.md, anthos-bm-edge-deployment/docs/ONE_TIME_SETUP.md
- Update variable names
- Update READMEs where it is used
- N/A
=> chore: update MACHINE-COUNT to GCE-COUNT

anthos-bm-gcp-terraform/resources/install_abm.sh
=> feat: [anthos-bm-gcp-terraform] set nfs-csi rwx

.github/trusted-contribution.yml
I noticed that dependabot is also utilized.
- #573
=> chore: add dependabot[bot] as trustedContributor

anthos-multi-cloud/AWS/terraform.tfvars
Update platform version to 1.25.5-gke.2000
=> chore: update gke version in terraform.tfvars

anthos-multi-cloud/Azure/terraform.tfvars
update platform version for Azure to 1.25.5-gke.2000
=> chore: update azure version in terraform.tfvars

anthos-bm-gcp-bash/install_hybrid_cluster.sh
=> fix: quote printf content

anthos-onprem-terraform/abm_user_cluster_metallb/main.tf, anthos-onprem-terraform/abm_user_cluster_metallb/versions.tf, anthos-onprem-terraform/avmw_user_cluster_metallb/README.md, anthos-onprem-terraform/avmw_user_cluster_metallb/main.tf, anthos-onprem-terraform/avmw_user_cluster_metallb/terraform.tfvars.sample, anthos-onprem-terraform/avmw_user_cluster_metallb/variables.tf, anthos-onprem-terraform/avmw_user_cluster_metallb/versions.tf
AVWM resources have been released in google-beta provider. Updating the sample files using google-beta provider instead
- Convert provider in main.tf to google-beta
=> fix: update TF sample files of AVMW for beta release

anthos-onprem-terraform/README.md
Removed "coming soon", added links to each resource in the Terraform registry, and some minor edits.
=> doc: update anthos-onprem-terraform README.md

anthos-onprem-terraform/avmw_user_cluster_metallb/README.md
=> chore: update doc link for updating platform controller version

.github/workflows/scorecards-analysis.yml
This PR disables the scorecard workflow.
=> Disable scorecard workflow

anthos-attached-clusters/kind/README.md, anthos-attached-clusters/kind/main.tf, anthos-attached-clusters/kind/outputs.tf
- Simplify user experience with outputs
=> feat: kind outputs

.github/.release-please-manifest.json, .github/release-please-config.json, .github/release-please.yml
Separately release
- anthos-bm-gcp-terraform (existing)
- anthos-attached-clusters (new)
=> chore: add release-please manifest config

README.md
This PR fixes the grammar in the README to conform to English conventions (periods, etc)
=> chore: fix grammar in README

anthos-bm-gcp-bash/install_admin_cluster.sh, anthos-bm-gcp-terraform/main.tf, test/integration/anthos_attached_clusters_kind/anthos_attached_clusters_kind_test.go
fix some minor issues in install_admin_cluster.sh
=> fix: update install_admin_cluster.sh

.github/gh_actions.md, .github/pull_request_template.md, .github/release.md
=> docs: Fixed Typos
