attached-logging-monitoring/logging/forwarder.yaml

- we may see warning from fluentd about failing to parse log message,
which can be confusing
- currently we only focus on sending logs from pods/containers to Cloud
Logging.
Signed-off-by: Yu Yi <yiyu@google.com>

Do not send kubelet logs since its format varies from k8s versions

---

renovate.json

- PRs open by renovate were failing CI due to `conventional commit` failures
- Fixing this by adding `:semanticCommits` to renovate.json

chore: Add semantic commit types to renovate.json

---

anthos-bm-gcp-terraform/modules/vm/main.tf

- Latest release of [terraform-google-vm](https://github.com/terraform-google-modules/terraform-google-vm/releases) breaks the vm module due to the `instance_details` output being `sensitive`
- Pin the version for the  [terraform-google-vm](https://github.com/terraform-google-modules/terraform-google-vm) module to `~> 6.3.0` so that on patch versions on 6.3 are included

fix: version pin terraform-google-vm module to ~> 6.3.0

---

aws-logging-monitoring/README.md
aws-logging-monitoring/monitoring/dashboards/pod-status.json

Provide sample cloud monitoring dashboard config file to monitor container status in Anthos on AWS clusters.
Sample config file based from Anthos on-prem(VMware) monitoring dashboard [instructions](https://cloud.google.com/anthos/clusters/docs/on-prem/how-to/logging-and-monitoring#dashboards).

feat: add monitoring dashboard for multicloud/aws

---

.github/README.md
.github/gh_runner_dependencies.sh
.github/workflows/ci_any_pr.yaml
.github/workflows/ci_master_branch.yaml

- Github actions runner was in a personal project under `runcible.org`
- The Github actions runners for all the Anthos/GKE samples should ideally be one project
- Added new runner in the `anthos-gke-samples-ci` project and configured this PR to start running on it

process: Add new Github runner in the anthos-gke-samples-ci project

---

anthos-bm-gcp-terraform/resources/run_initialization_checks.sh

- The issue was with bash expansion with single quoted variables
- The issue could be fixed by replacing the single quotes with double quotes
- Add double quotes instead of single quotes

fix: bash trap signal error on gce-tf sample initialization script

---

anthos-bm-gcp-terraform/resources/anthos_gce_cluster.tpl
anthos-bm-gcp-terraform/resources/init.sh
test/integration/abm_gce_defaults_on_editor_project/controls/gcloud.rb
test/integration/abm_gce_defaults_on_owner_project/controls/gcloud.rb

- `bmctl` version needs to be updated to latest minor version
- Update `bmctl` CLI version in the initialization script
- Update the `bmctl` version in the `cluster.yaml` configuration
- Update the `bmctl` version in the integrationtests
- #69

release: update bmctl version to 1.8.0

---

anthos-bm-gcp-terraform/main.tf

- #70
- The terraform apply fails when project wide oslogin is enabled with ssh error.
- Add oslogin metadata to instance template to override project wide setting

feat: add oslogin metadata to override project wide setting

---

.github/gh_runner_dependencies.sh
.github/workflows/ci_any_pr.yaml
.github/workflows/ci_master_branch.yaml
Makefile
anthos-bm-gcp-terraform/README.md
anthos-bm-gcp-terraform/versions.tf
build/int.cloudbuild.yaml
build/lint.cloudbuild.yaml
test/setup/versions.tf

- bump devtools version
- relax module version constraint to support TF 1.0+

chore: bump devtools version, relax module version constraint

---

aws-logging-monitoring/monitoring/gke-metrics-agent.yaml

- Support application metrics in Cloud Monitoring for Anthos MultiCloud on AWS (k-lite version)
- Add the configs to scrape application metrics with prometheus annotations
- #8 
- #57 
Signed-off-by: Leon Ziyang Zhang <leonzz@google.com>

feat: application metrics for multicloud/aws klite

---

README.md

Currently the badge is 404ing. 
I think it should be this? https://github.com/GoogleCloudPlatform/anthos-samples/workflows/Continuous%20Integration%20-%20Main/Release/badge.svg

cleanup: update CI badge on README

---

CODEOWNERS

- New PR #124 adds Anthos multi-cloud samples into the repo
- We need to delegate approval ownership to the contributors who work on that 
- Create a new Github team called [anthos-multicloud](https://github.com/orgs/GoogleCloudPlatform/teams/anthos-multicloud/members) 
- Add the requested contributors _(as shared by the contributor of PR #124) to the new team
- Add that team as the CodeOwners of the `anthos-multi-cloud` sample directory

chore: add a new team anthos-multicloud as owners

---

anthos-multi-cloud/Azure/modules/gcp_data/main.tf

in Azure example instead of google_container_aws_versions.

fix: use google_container_azure_versions data src

---

anthos-multi-cloud/AWS/provider.tf

Fixes #178
- Remove hardcoded AWS profile name from GKE on AWS
- Terraform
- One line removed
- Fixed whitespaces after parameter was removed

cleanup: remove hardcoded profile in AWS provider for GKE on AWS

---

anthos-bm-gcp-terraform/test/unit/main_test.go
anthos-bm-gcp-terraform/test/unit/module_external_ip_test.go
anthos-bm-gcp-terraform/test/unit/module_init_test.go
anthos-bm-gcp-terraform/test/unit/module_vm_test.go
anthos-bm-gcp-terraform/test/util/cluster_yaml.go
anthos-bm-gcp-terraform/test/util/functions.go
anthos-bm-gcp-terraform/test/util/module_external_ip.go
anthos-bm-gcp-terraform/test/util/module_init.go
anthos-bm-gcp-terraform/test/util/module_main.go
anthos-bm-gcp-terraform/test/util/module_vm.go
anthos-bm-gcp-terraform/test/util/tf_module.go

- Add the issue explained in https://github.com/GoogleCloudPlatform/anthos-samples/issues/47
- The reason for the issue has been [fixed in the cloud-foundation-toolkit repo](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/926)
- So now we can fix it in our end
- Remove the `nolint` handles
- Regenerate the license headers using [addlicense](https://github.com/google/addlicense)
- NA

fix: regenerate go file licenses with addlicense tool

---

anthos-bm-gcp-terraform/main.tf
anthos-bm-gcp-terraform/modules/vm/main.tf
anthos-bm-gcp-terraform/modules/vm/variables.tf
anthos-bm-gcp-terraform/test/unit/main_test.go
anthos-bm-gcp-terraform/test/unit/module_external_ip_test.go
anthos-bm-gcp-terraform/test/unit/module_init_test.go
anthos-bm-gcp-terraform/test/unit/module_vm_test.go
anthos-bm-gcp-terraform/test/util/cluster_yaml.go
anthos-bm-gcp-terraform/test/util/functions.go
anthos-bm-gcp-terraform/test/util/module_external_ip.go
anthos-bm-gcp-terraform/test/util/module_init.go
anthos-bm-gcp-terraform/test/util/module_main.go
anthos-bm-gcp-terraform/test/util/module_vm.go
anthos-bm-gcp-terraform/test/util/tf_module.go

- Please read the description from the issue #186 
- We fix the issue by passing in the zone information to the VM creation module.
- This PR also has fixes from https://github.com/GoogleCloudPlatform/anthos-samples/pull/191. It was mistakenly merged into this because the wrong branch being set there

fix: zone mismatch for vm

---

anthos-multi-cloud/AWS/modules/iam/main.tf

to include ec2:ModifyNetworkInterfaceAttribute. This is a new required IAM permission [0].
[0] https://cloud.google.com/anthos/clusters/docs/multi-cloud/aws/how-to/create-aws-iam-roles#create_role.

fix: update API IAM policy

---

anthos-bm-gcp-terraform/main.tf
anthos-bm-gcp-terraform/test/unit/main_test.go
anthos-bm-gcp-terraform/test/util/module_main.go
anthos-bm-gcp-terraform/test/util/tf_module.go
anthos-bm-gcp-terraform/test/validation/main_test_validation.go
anthos-bm-gcp-terraform/variables.tf

- Enable nested virtualization support for better performance using [Anthos VM Runtime](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/how-to/vm-workloads) on [Anthos Baremetal on GCE](https://github.com/GoogleCloudPlatform/anthos-samples/tree/main/anthos-bm-gcp-terraform).
- Adds `enable_nested_virtualization` to instance_template
- Add `var.enable_nested_virtualization` to `variable.tf`, default is enabled.
- Adds tests for `enable_nested_virtualization` and `var.enable_nested_virtualization`

feat: Enable nested virtualization support for ABM Terraform installation on GCE

---

anthos-bm-gcp-terraform/resources/anthos_gce_cluster.tpl
anthos-bm-gcp-terraform/resources/init_vm.sh
anthos-bm-gcp-terraform/versions.tf

- Update anthos-bm-gcp-terraform to Anthos Baremetal (bmctl) [1.10.2](https://cloud.google.com/anthos/clusters/docs/bare-metal/1.8/release-notes#release_1102)
- Update anthos-bm-gcp-terraform to ABM 1.10.2

chore: Update anthos-bm-gcp-terraform to ABM 1.10.2

---

CODEOWNERS

Error in the CODEOWNERS file
- I noticed that there was no existing group `googleapis/cdpe-devplat`, saw that it was incorrectly written instead of being `@GoogleCloudPlatform/cdpe-devplat`
~Changed~ Removed  `googleapis/cdpe-devplat` ~to @GoogleCloudPlatform/cdpe-devplat~
n/a!

chore: Update Codeowners

---

.github/workflows/ci_any_pr.yaml

- The CI flakiness started after some recent changes to the github actions
- In an attempt to figure this out I am trying to remove the recently added tf-docs github actions plugin
- It seems like the issue started close to when this was introduced.
- Remove all tf-docs specific CI steps
- N.A

cleanup: remove tfdocs

---

anthos-multi-cloud/AWS/main.tf
anthos-multi-cloud/AWS/modules/anthos_cluster/main.tf
anthos-multi-cloud/AWS/modules/anthos_cluster/variables.tf
anthos-multi-cloud/AWS/provider.tf
anthos-multi-cloud/AWS/terraform.tfvars
anthos-multi-cloud/AWS/variables.tf

- Allow setting multiple admin users for Anthos clusters on AWS.

feat: Allow setting multiple admin users.

---

anthos-bm-gcp-terraform/docs/variables.md
anthos-bm-gcp-terraform/main.tf
anthos-bm-gcp-terraform/test/unit/main_custom_mode_test.go
anthos-bm-gcp-terraform/test/unit/main_test.go

- For install modes automatically deletes the GKE hub membership during the TF destroy.

feat: [anthos-bm-gcp-terraform] auto remove gke hub membership

---

anthos-bm-gcp-terraform/resources/init_vm.sh

- Removes disable AppArmor as it is [supported](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/installing/configure-os/ubuntu#before_you_begin) in Anthos clusters on bare metal v1.8.2+.

feat: [anthos-bm-gcp-terraform] add back AppArmor

---

anthos-multi-cloud/AWS/modules/vpc/main.tf

- Any aws_route_table resources created should have the `count.index` interpolated in the `Name` tag rather than read in as a string
- In a vpc called my-vpc, this change will create route tables called `my-vpc-public-1`, `my-vpc-public-2`, `my-vpc-public-3` rather than 3 subnets all called `my-vpc-public-[count.index]`.
- Corrected tag definition of aws_route_table resources to correctly interpolate the value of `count.index`

fix: AWS route_table names interpolating variables

---

anthos-vmruntime/README.md
anthos-vmruntime/pos-service.yaml

Use service selector with the anthos-vmruntime VM, this also enables live migration of the VM.

feat: [anthos-vmruntime] use service selector with 

---

anthos-multi-cloud/AWS/modules/iam/main.tf

According to https://cloud.google.com/anthos/clusters/docs/multi-cloud/aws/how-to/create-aws-iam-roles
AWS: CP nodes need `ec2:GetConsoleOutput` IAM permission
- CP Instances wont be successfully provisioned due to missing IAM permission
- Add missing AWS IAM permission to `API_ROLE`

fix: [anthos-multi-cloud] Missing AWS IAM role policies for CP

---

anthos-bm-edge-deployment/roles/abm-login-token/tasks/get-login-token.yaml
anthos-bm-edge-deployment/scripts/cloud/cnuc-k8s-login-setup.sh
anthos-bm-gcp-terraform/resources/login.sh
anthos-bm-openstack-terraform/resources/abm_cluster_login.sh

Fixes #306
The .secrets field within service accounts is only for listing secrets
to be mounted into pods, not for extracting secrets for other uses.
There is no guarantee the first item in the list will be a token secret.
In 1.24+, this field is not populated by default.
Adapt instructions from https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token to obtain a token
cc @zshihang

Fix method of obtaining service account token

---

anthos-bm-gcp-terraform/resources/templates/anthos_gce_cluster.tpl
anthos-bm-gcp-terraform/resources/templates/manuallb_cluster.tpl
anthos-bm-openstack-terraform/resources/abm_cluster.yaml.tpl
anthos-vmruntime/README.md
anthos-vmruntime/pos-vm.yaml

- All resources besides the anthos-bm-gcp-terraform template had 'local-shared' as the `storageClassName`.
- Changed the template to have `storageClassName: local-shared` 
n/a

fix: Changed storageclass name

---

anthos-multi-cloud/AWS/main.tf
anthos-multi-cloud/AWS/modules/anthos_cluster/main.tf
anthos-multi-cloud/AWS/modules/anthos_cluster/variables.tf
anthos-multi-cloud/AWS/modules/iam/main.tf
anthos-multi-cloud/AWS/modules/iam/variables.tf
anthos-multi-cloud/AWS/modules/kms/main.tf
anthos-multi-cloud/AWS/modules/kms/outputs.tf
anthos-multi-cloud/AWS/modules/kms/variables.tf

- Create different AWS KMS keys and provides examples on how to set permissions to create a k8s cluster
- Added 5 new KMS keys on different purpose based on https://cloud.google.com/anthos/clusters/docs/multi-cloud/aws/how-to/create-aws-kms-key
- Pass arns of the keys to module iam to set the iam policy
- Update module `anthos_cluster` to use these kms keys
- Separate iam_instance_profile into control_plane_iam_instance_profile & node_pool_iam_instance_profile for module `anthos_cluster` to reflect different permission requirement
- N/A

feat: add KMS keys permission examples

---

anthos-multi-cloud/AWS/modules/iam_scope_down/README.md
anthos-multi-cloud/AWS/modules/iam_scope_down/main.tf
anthos-multi-cloud/AWS/modules/iam_scope_down/outputs.tf
anthos-multi-cloud/AWS/modules/iam_scope_down/variables.tf

- Showcase how to restrict access of roles assumed by `Anthos Multi-Cloud API service agent`, `cluster control plane` and `cluster node pool` based on *resource name prefix* and *AWS tags*.
- Add a module `iam_scope_down`
- Add README on how to use this module

feat: add module `iam_scope_down`

---

anthos-multi-cloud/AWS/README.md
anthos-multi-cloud/AWS/outputs.tf
anthos-multi-cloud/Azure/README.md
anthos-multi-cloud/Azure/outputs.tf

- Use AMC commands as listed at
- https://cloud.google.com/anthos/clusters/docs/multi-cloud/aws/how-to/connect-and-authenticate-to-your-cluster
- https://cloud.google.com/anthos/clusters/docs/multi-cloud/azure/how-to/connect-and-authenticate-to-your-cluster
- Replace `gcloud container hub memberships get-credentials` with
- `gcloud container aws clusters get-credentials`
- `gcloud container azure clusters get-credentials`
- N/A

fix: Use AMC commands instead of Hub commands to get kubeconfig

---

anthos-bm-gcp-terraform/docs/manuallb_install.md

- Fixed the hardcoded cluster name in gcloud command
- removed `cluster1` with `${CLUTER_ID}`
https://github.com/GoogleCloudPlatform/anthos-samples/issues/282

fix: replaced cluster-1 with variable

---

anthos-bm-utils/abm-nettest/nettest.yaml
anthos-bm-utils/abm-nettest/nettest_rhel.yaml

- uses the latest nettest images from `anthos-baremetal-release`
- changes the prober name to use `node` instead of `vm`

chore: update images in nettest

---

anthos-bm-utils/abm-nettest/nettest.yaml
anthos-bm-utils/abm-nettest/nettest_rhel.yaml

- Updates nettest version to 0.3.2, which fixes the issue where nettest cannot run on baremetal nodes.

chore: updates nettest version to 0.3.2

---

attached-logging-monitoring/logging/aggregator.yaml
attached-logging-monitoring/logging/forwarder.yaml
attached-logging-monitoring/monitoring/prometheus.yaml

- Added a linux OS nodeselctor on all logmon agents for attached cluster.
- also related to #6 which asks for a solution for Windows.

fix: prevent logmon to run on unsupported win node

---

anthos-vmruntime/README.md
anthos-vmruntime/pos-service.yaml
anthos-vmruntime/pos-vm.yaml

- Updates anthos-vmruntime for ABM 1.12
anthos-vmruntime
- Cli `--cpu` is now `--vcpus`
- Updated expected output to 1.12 format
- Added `VirtualMachineDisk` cli example
- Updated .yaml files to VM Runtime v1 syntax
- Updated `vm.cluster.gke.io/vm-name` is now `kubevirt/vm`

feat: update anthos-vmruntime example for ABM 1.12

---

anthos-bm-gcp-bash/setup_and_install_abm.sh

Enable connectgateway.googleapis.com so we can demonstrate `gcloud container fleet memberships get-credentials` in the tutorial.

chore: ypdate setup_and_install_abm.sh

---

anthos-bm-gcp-bash/install_admin_cluster.sh

- The [admin cluster creation script](https://github.com/GoogleCloudPlatform/anthos-samples/blob/main/anthos-bm-gcp-bash/install_admin_cluster.sh#L264) is pinned to a specific version
- Ideally we would want this to be updated depending on the doc version that is being viewed, rather than pinned to a specific version 
- Add a new environment variable for the bmctl version
- Provide that environment variable as a metadata to the VMs
- Fetch that version from inside the vm before creatng the cluster config and the cluster itself
- N/A

chore: add bmctl version variable

---

anthos-bm-gcp-bash/install_hybrid_cluster.sh
anthos-bm-gcp-terraform/resources/init_vm.sh
anthos-bm-gcp-terraform/resources/templates/anthos_gce_cluster.tpl
anthos-bm-gcp-terraform/resources/templates/manuallb_cluster.tpl
anthos-bm-gcp-terraform/test/unit/main_test.go
anthos-bm-gcp-terraform/variables.tf
anthos-bm-gcp-terraform/versions.tf
test/integration/abm_gce_defaults_on_editor_project/abm_gce_editor_test.go

- Update ABM version to 1.14.0
- Update ABM version to 1.14.0
- Add `connectgateway.googleapis.com` API as that is now required by ABM: https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/installing/configure-sa#enable_apis

feat: update ABM version to 1.14.0

---

renovate.json

- Renovate is continuously trying to increase versions of Ansible and other dependencies related to the [anthos-bm-edge-deployment](https://github.com/GoogleCloudPlatform/anthos-samples/tree/main/anthos-bm-edge-deployment) sample
- This sample is a mirror of an internal repo and should only be updated according to the internal repo changes
- Thus, setting up renovate to not include this sample in its scanning.
- Add the directory path to the anthos-bm-edge-deployment sample in renovate configs
- N/A

cleanup: renovate skip anthos-bm-edge-deployment sample

---

anthos-bm-gcp-bash/install_hybrid_cluster.sh

- This is related to PR #531 
- It updates one script to fail fast; but there is another one that needs the same change.
- The comment to update that also was not responded to
- So I merged it and openned the update myself
- Update the `install_hybrid_cluster` script to have the fail fast shell flag
- https://github.com/GoogleCloudPlatform/anthos-samples/pull/531

chore: add shell fail fast flag to the install_hybrid_cluster script

---

anthos-bm-gcp-bash/install_admin_cluster.sh
anthos-bm-gcp-bash/install_hybrid_cluster.sh

- The step to download the bmctl CLI has the ABM version hardcoded
- The step to install the cluster in [the doc (that uses this script)](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/try/gce-vms#deploy_an_hybrid_cluster) the version is taken from the devsite variable `current_patch`.
- As a result when this doc is released for the new versions of ABM we have to make sure we update this script also to reflect that change. 
- This will impact previous versions of the documentation
- Thus, we extract the ABM version as a variable in this PR
- We then will update the docs to add an additional step to mention the ABM version at the beginning. We will set `current_patch` as the default version on different releases of the documentation
- You can see [this …

improvement: use variables for ABM version

---

anthos-bm-gcp-terraform/main.tf
anthos-bm-gcp-terraform/outputs.tf
anthos-bm-gcp-terraform/resources/init_vm.sh
anthos-bm-gcp-terraform/resources/templates/anthos_gce_cluster.tpl
anthos-bm-gcp-terraform/resources/templates/init.vars.tpl
anthos-bm-gcp-terraform/resources/templates/manuallb_cluster.tpl
anthos-bm-gcp-terraform/variables.tf
anthos-bm-gcp-terraform/versions.tf
test/fixtures/abm_gce_defaults_on_editor_project/outputs.tf
test/integration/abm_gce_defaults_on_editor_project/abm_gce_editor_test.go

- Parameterize ABM version to a single `abm_version` variable rather than hard coded
- Set default `abm_version` to 1.14.1
- Updates the test to use `abm_version` instead of using hard coded

feat: [anthos-bm-gcp-terraform] parameterize ABM version

---

.github/trusted-contribution.yml

- add `trusted-contribution.yml` for use with https://github.com/googleapis/repo-automation-bots
- Automatically adds `/gcbrun` to PRs from listed Contributors

chore: add trusted-contribution

---

.github/trusted-contribution.yml

This PR adds another entry for Renovate called `renovate-bot` in the trusted-contribution. This is to make sure to catch any instances of the Renovate bot opening PRs against this repository, which are currently not all caught (for example: https://github.com/GoogleCloudPlatform/anthos-samples/pull/590).

chore: Fix Renovate in trusted-contribution

---

anthos-bm-gcp-bash/install_admin_cluster.sh

Change the service CIDR to 10.96.0.0/20, which is the default used in the docs and UI.

chore: update install_admin_cluster.sh

---

anthos-bm-utils/abm-nettest/nettest.yaml
anthos-bm-utils/abm-nettest/nettest_rhel.yaml

This version includes logic to create cloudprobers with correct toleration for CP nodes.
The manifest also includes correct toleration for echoserver, while choosing 9222 as a port, to reduce likelihood of port collision with others.
- This change enables running nettest on CP nodes as well to check network connectivity CP nodes and other k8s nodes/pods/svcs.

improvement: update nettest manifests to version v0.3.7-gke.9__linux_amd64

---

anthos-multi-cloud/AWS/README.md
anthos-multi-cloud/AWS/modules/iam/main.tf
anthos-multi-cloud/AWS/modules/iam_scope_down/main.tf
anthos-multi-cloud/AWS/terraform.tfvars
anthos-multi-cloud/Azure/README.md
anthos-multi-cloud/Azure/terraform.tfvars

- Update AWS/Azure READMEs with instructions for setting `cluster_version` with link to supported versions. 
- Add missing permission `iam:GetInstanceProfile` for AWS

Update AWS/Azure READMEs with instructions for setting `cluster_version` and add missing permission for AWS

---

.gitignore
anthos-attached-clusters/kind/README.md
anthos-attached-clusters/kind/main.tf
anthos-attached-clusters/kind/oidc/main.tf
anthos-attached-clusters/kind/oidc/outputs.tf
anthos-attached-clusters/kind/oidc/providers.tf
anthos-attached-clusters/kind/oidc/variables.tf
anthos-attached-clusters/kind/provider.tf
anthos-attached-clusters/kind/variables.tf

[feat: add an attached cluster example for kind as well #673](https://github.com/GoogleCloudPlatform/anthos-samples/issues/673)
in addition to the actual business cases for AKS and EKS, it might be nice to provide a trial example for [kind](https://kind.sigs.k8s.io/) as well.
just adds a kind example

feat: add an attached cluster example for kind as well

---

.github/workflows/lint.yaml
anthos-attached-clusters/kind/README.md
anthos-bm-apigee/docs/variables.md
anthos-bm-apigee/versions.tf
anthos-bm-gcp-bash/install_admin_cluster.sh
anthos-bm-gcp-terraform/docs/variables.md
anthos-bm-gcp-terraform/main.tf
anthos-bm-gcp-terraform/terraform.tfvars.sample
anthos-bm-gcp-terraform/variables.tf
anthos-bm-openstack-terraform/resources/abm_cluster_login.sh
anthos-bm-openstack-terraform/resources/abm_init_host.sh
anthos-bm-openstack-terraform/resources/abm_setup_gcp.sh
anthos-bm-openstack-terraform/resources/cloud-config.yaml
anthos-bm-openstack-terraform/resources/create-certs.sh
anthos-multi-cloud/AWS/README.md
anthos-onprem-terraform/README.md
anthos-onprem-terraform/avmw_user_cluster_metallb/README.md
anthos-onprem-terraform/avmw_user_cluster_metallb/main.tf
test/fixtures/abm_gce_gpu/main.tf
test/integration/abm_gce_defaults_on_editor_project/abm_gce_editor_test.go
test/integration/abm_gce_gpu/controls/gcloud.rb

- Updates to restore Integration test (abm-gce-gpu)
- Switched to currently available GPU type/location, and allocate only to worker nodes
- With the new dedicated worker node template, also removed nested virtualization from control plane and admin workstation as not required
- Updates to fix and re-enable (migrated from cloudbuild trigger to GH workflow) Lint tests

fix(CI): updates to restore CI lint and integration tests

---

anthos-attached-clusters/aks/main.tf
anthos-attached-clusters/aks/provider.tf
anthos-attached-clusters/eks/provider.tf
anthos-attached-clusters/kind/README.md
anthos-attached-clusters/kind/oidc/providers.tf
anthos-attached-clusters/kind/provider.tf
anthos-attached-clusters/modules/attached-install-manifest/provider.tf

- Add any missing providers and versions constraints
- Additional lint fixes

fix(anthos-attached-clusters): add providers and lint

---

anthos-bm-apigee/main.tf
anthos-bm-apigee/variables.tf
anthos-bm-gcp-terraform/main.tf
anthos-bm-gcp-terraform/modules/loadbalancer/variables.tf
anthos-bm-gcp-terraform/modules/vm/outputs.tf
anthos-bm-gcp-terraform/variables.tf
anthos-multi-cloud/AWS/main.tf
anthos-multi-cloud/AWS/modules/kms/main.tf
anthos-multi-cloud/AWS/modules/vpc/variables.tf
anthos-multi-cloud/AWS/provider.tf
anthos-multi-cloud/AWS/variables.tf
anthos-multi-cloud/Azure/main.tf
anthos-multi-cloud/Azure/modules/anthos_cluster/variables.tf
anthos-multi-cloud/Azure/modules/cluster-rg/main.tf
anthos-multi-cloud/Azure/modules/cluster-vnet/variables.tf
anthos-onprem-terraform/abm_user_cluster_manuallb/variables.tf
anthos-onprem-terraform/abm_user_cluster_metallb/variables.tf
anthos-onprem-terraform/avmw_user_cluster_metallb/variables.tf

- remove unused data and variables (and associated plumbing)
- add version constraints
- minor terraform updates

fix: minor updates for lint

---

renovate.json

Update to recommendations from `renovate-config-validator`
```shell
% npx -p renovate renovate-config-validator
Need to install the following packages:
renovate@38.77.8
Ok to proceed? (y) y
INFO: Validating renovate.json
WARN: Config migration necessary
"oldConfig": {
[...]
```
After
```
% npx -p renovate renovate-config-validator   
INFO: Validating renovate.json
INFO: Config validated successfully
```
- Update Renovate config

chore: migrate renovate config

---

anthos-bm-edge-deployment/scripts/create-primary-gsa.sh

Service account creation script in the edge deployment scenario enables the Cloud Source Repositories API which are now deprecated.  CSR is not used in the deployment and so this can be removed.
- Removes command to enable CSR API
- closes #745

fix: remove line that enables Cloud Source Repositories API as this is now deprecated

---

anthos-bm-gcp-bash/install_admin_cluster.sh

General updates
- Fix some typos
- root login was not working, so I changed to login as a user and change to root
- ensure appropriate permissions exist to be able to write the ssh key as metadata

fix: update install_admin_cluster.sh

---

.github/workflows/ci_any_pr.yaml

`actions/checkout`, by default, checks-out the current PR, so there is no need to explicitly give it a ref.
- Removed the redundant `with.ref` statements, as the PR is, by default, the branch that is checked-out.

chore: remove redundant `with`
